# Generated by Django 5.2.16 on 2026-07-26 19:54

from django.db import migrations, models


def seed_initial_movies(apps, schema_editor):
    Movie = apps.get_model('pages', 'Movie')
    initial_movies = [
        ("Backrooms", 2026),
        ("Obsession", 2026),
        ("The Odyssey", 2026),
        ("Toy Story 5", 2026),
    ]

    for title, year in initial_movies:
        Movie.objects.get_or_create(title=title, year=year)


def unseed_initial_movies(apps, schema_editor):
    Movie = apps.get_model('pages', 'Movie')
    initial_movies = [
        ("Backrooms", 2026),
        ("Obsession", 2026),
        ("The Odyssey", 2026),
        ("Toy Story 5", 2026),
    ]

    for title, year in initial_movies:
        Movie.objects.filter(title=title, year=year).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_moviereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', 'year'],
                'constraints': [models.UniqueConstraint(fields=('title', 'year'), name='unique_movie_title_year')],
            },
        ),
        migrations.RunPython(seed_initial_movies, unseed_initial_movies),
    ]
