# Generated by Django 5.2.16 on 2026-07-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
